
# Site settings
title: Yaquan Chang
name: Yaquan Chang
subtitle: PhD in Macroecology
email: yaquanchang0623@gmail.com
description: >
  PhD 
baseurl: ""
url: "https://yaquanchang.github.io/"
github_username:  YaquanChang
disqus_baseurl: "https://yaquanchang.github.io/"
disqus_shortname: https-yaquanchang-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yaquan Chang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: Twitter
    icon: twitter
    username: YaquanChang
    url: https://twitter.com/YaquanChang/
    desc: Follow me on Twitter
    share: false

  - name: ResearchGate
    icon: researchgate
    username: Yaquan Chang
    url: https://www.researchgate.net/profile/Yaquan_Chang2
    desc: Connect with me on ResearchGate
    share: true
